---
- hosts: localhost
  vars_files:
    - config/defaults.yaml
    - config/secrets.yaml
  handlers:

    - name: restart sssd
      service:
        name: sssd
        state: restarted

  tasks:

        # Include host vars if they exist
    - include_vars: "/usr/local/etc/baseline/config.yaml"
      failed_when: false

    - name: system-baseline | configure dns
      block:

      - name: dns | configure nameservers
        template:
          src: "../templates/dns/resolv.conf.j2"
          dest: "/etc/resolv.conf"
          mode: "0755"
          owner: "root"
          group: "wheel"
        tags:
          - dns
          - dns:configure
      tags:
        - dns
      when: configure_dns | default(True)

    - name: system-baseline | install packages
      package:
        name:
          - sssd2
          - bash
          - pam_mkhomedir
          - sudo
      tags:
        - baseline
        - baseline:packages

    - name: system-baseline | deploy motd
      with_items:
        - /etc/motd
        - /var/run/motd
      copy:
        dest: "{{item}}"
        content: |+
          $
                          __
                         / _)
                _.----._/ /
               /         /
            __/ (  | (  | It's a UNIX System!
           /__.-'|_|--|_|    I know this!  

    - name: system-baseline | create directories
      ansible.builtin.file:
        path: "{{item}}"
        state: directory
      with_items:
        - /home
        - /usr/local/etc/pkg/repos
        - /usr/share/skel

    - name: baseline-freebsd | deploy file templates
      ansible.builtin.template:
        src: "../templates/{{item.template}}"
        dest: "{{item.dest}}"
        mode: "{{item.mode}}"
      notify: "restart sssd"
      with_items:
        # SSSD
        - { template: sssd/sssd.conf.j2,  dest: /usr/local/etc/sssd/sssd.conf, mode: "0600" }

        # PAM
        - { template: pam/system,  dest: /etc/pam.d/system, mode: "0644"}
        - { template: pam/sshd,  dest: /etc/pam.d/sshd,    mode: "0644"}

        # Sudo
        - { template: sudoers/sudoers,  dest: /usr/local/etc/sudoers, mode: "0440" }

        # nsswitch
        - { template: nsswitch/nsswitch.conf,  dest: /etc/nsswitch.conf, mode: "0644" }

        #/usr/local/etc/pkg/repos/FreeBSD.conf
        - { template: pkg/FreeBSD.conf,  dest: /usr/local/etc/pkg/repos/FreeBSD.conf, mode: "0644" }

        # SSH
        - { template: ssh/sshd_config,  dest: /etc/ssh/sshd_config, mode: "0644" }

        # Cron
        - { template: cron/baseline,  dest: /etc/cron.d/baseline, mode: "0644" }

        # Skel
        - { template: skel/dot.bashrc,  dest: /usr/share/skel/dot.bashrc, mode: "0644" }
        - { template: skel/dot.bash_profile,  dest: /usr/share/skel/dot.bash_profile, mode: "0644" }

    - name: baseline-freebsd | start services
      service:
        name: "sssd"
        state: started
        enabled: yes

    - name: baseline-freebsd | download ssh keys
      ansible.builtin.get_url:
        url: "{{item.url}}"
        dest: /home/{{item.name}}/.ssh/authorized_keys
        mode: '0600'
        owner: "{{item.name}}"
        group: "grp-sigaint-users"
      with_items: "{{user_ssh_keys}}"
      ignore_errors: true
