---
- hosts: localhost
  vars_files:
    - config/defaults.yaml
  handlers:

    - name: restart sssd
      service:
        name: sssd
        state: restarted

  tasks:

    - name: system-baseline | configure dns
      block:

      - name: dns | configure nameservers
        template:
          src: "../templates/dns/resolv.conf.j2"
          dest: "/etc/resolv.conf"
          mode: "0755"
          owner: "root"
          group: "wheel"
        tags:
          - dns
          - dns:configure
      tags:
        - dns

    - name: system-baseline | install packages
      package:
        name:
          - sssd2
          - bash
          - pam_mkhomedir
          - sudo
      tags:
        - baseline
        - baseline:packages


    - name: openldap-freebsd | create directories
      ansible.builtin.file:
        path: "{{item}}"
        state: directory
      with_items:
        - /home
        - /usr/local/etc/pkg/repos

    - name: openldap-freebsd | deploy file templates
      ansible.builtin.template:
        src: "../templates/{{item.template}}"
        dest: "{{item.dest}}"
        mode: "{{item.mode}}"
      notify: "restart sssd"
      with_items:
        # SSSD
        - { template: sssd/sssd.conf.j2,  dest: /usr/local/etc/sssd/sssd.conf, mode: "0600" }

        # PAM
        - { template: pam/system,  dest: /etc/pam.d/system, mode: "0644"}
        - { template: pam/sshd,  dest: /etc/pam.d/sshd,    mode: "0644"}

        # Sudo
        - { template: sudoers/sudoers,  dest: /usr/local/etc/sudoers, mode: "0440" }

        # nsswitch
        - { template: nsswitch/nsswitch.conf,  dest: /etc/nsswitch.conf, mode: "0644" }

        #pkg
        #/usr/local/etc/pkg/repos/FreeBSD.conf
        - { template: pkg/FreeBSD.conf,  dest: /usr/local/etc/pkg/repos/FreeBSD.conf, mode: "0644" }
