---
- hosts: localhost
  vars_files:
  handlers:
    - include_tasks: "playbooks/handlers.yaml"
  tasks:
    # Include host vars if they exist
    - include_vars:
        - "config/defaults.yaml"
        - "/usr/local/etc/baseline/config.yaml"
        - "config/os/{{ansible_distribution | lower}}.yaml"
        - "config/secrets.yaml"
      failed_when: false
      tags:
        - always

    - block:
      - ansible.builtin.include_tasks: "playbooks/repos.yaml"
        when: configure_repos | default(true)

      - ansible.builtin.include_tasks: "playbooks/dns.yaml"
        when: configure_dns | default(true)

      - ansible.builtin.include_tasks: "playbooks/motd.yaml"
        when: configure_motd | default(true)

      - ansible.builtin.include_tasks: "playbooks/timezone.yaml"
        when: configure_timezone | default(true)

      - ansible.builtin.include_tasks: "playbooks/ntp.yaml"
        when: configure_ntp | default(true)

      - ansible.builtin.include_tasks: "playbooks/skel.yaml"
        when: configure_skel | default(true)

      - ansible.builtin.include_tasks: "playbooks/auth.yaml"
        when: configure_sssd | default(true)

      - ansible.builtin.include_tasks: "playbooks/sudoers.yaml"
        when: configure_sudoers | default(true)

      - ansible.builtin.include_tasks: "playbooks/sshd.yaml"
        when: configure_sshd | default(true)

      - ansible.builtin.include_tasks: "playbooks/baseline.yaml"
        when: configure_baseline | default(true)

      - ansible.builtin.include_tasks: "playbooks/syslog.yaml"
        when: configure_syslog | default(true)

      - ansible.builtin.include_tasks: "playbooks/moonlight.yaml"
        tags:
          - always