---
- hosts: localhost
  vars_files:
    - config/defaults.yaml
    - config/secrets.yaml
  handlers:
    - name: Restart sssd
      ansible.builtin.service:
        name: sssd
        state: restarted

  tasks:
    # Include host vars if they exist
    - ansible.builtin.include_vars: "/usr/local/etc/baseline/config.yaml"
      failed_when: false
      tags:
        - always

    - block:
      - ansible.builtin.import_tasks: "playbooks/dns.yaml"
        when: configure_dns | default(true)

      - ansible.builtin.import_tasks: "playbooks/motd.yaml"
        when: configure_motd | default(true)

      - ansible.builtin.import_tasks: "playbooks/skel.yaml"
        when: configure_skel | default(true)

      - ansible.builtin.import_tasks: "playbooks/sssd.yaml"
        when: configure_sssd | default(true)

      - ansible.builtin.import_tasks: "playbooks/sudoers.yaml"
        when: configure_sudoers | default(true)

      - ansible.builtin.import_tasks: "playbooks/sshd.yaml"
        when: configure_sshd | default(true)

      - ansible.builtin.import_tasks: "playbooks/baseline.yaml"
        when: configure_baseline | default(true)

      - ansible.builtin.import_tasks: "playbooks/moonlight.yaml"
        tags:
          - always