---
- name: sigaint-soe | cacert | get file stats
  ansible.builtin.stat:
    path: /etc/pki/ca-trust/source/anchors/ca.crt
  register: cert
  tags:
    - baseline:cacert
    - baseline:cacert:configure

- name: sigaint-soe | cacert | deploy cacert
  ansible.builtin.get_url:
    url: https://ipa-1.syd.sigaint.au/ipa/config/ca.crt
    dest: /etc/pki/ca-trust/source/anchors/ca.crt
    validate_certs: false
    mode: '0644'
    when: cert.exists
  tags:
    - baseline:cacert
    - baseline:cacert:configure
