---
- name: sigaint-soe | rsyslog | install packages
  ansible.builtin.package:
    name:
      - rsyslog
  tags:
    - baseline:rsyslog
    - baseline:rsyslog:packages

- name: sigaint-soe | auth | deploy templates
  ansible.builtin.template:
    src: "../templates/{{ item.template }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  notify: "restart rsyslog"
  with_items:
    - { template: /sssd.conf.j2, dest: /etc/sssd/sssd.conf, mode: "0600" }

- name: sigaint-soe | auth | start services
  ansible.builtin.service:
    name: "rsyslog"
    state: started
    enabled: true

