---
# http://127.0.0.1:3000/api/v1/machines/check_in"
moonlight_api: "https://moonlight.ts.sigaint.au/api/v1/machines/check_in"

dns_search:
  - sigaint.au
  - ts.sigaint.au

# Set system timezone
timezone: "Australia/Sydney"

# Set the default syslog server
syslog_server: "ingest.logs.sigaint.au:2514"

# NextDNS
dns_servers:
  - 45.90.28.189
  - 45.90.30.189
  - 2a07:a8c0::2a:b561
  - 2a07:a8c1::2a:b561

ntp_servers:
  - time1.google.com
  - time2.google.com
  - time3.google.com
  - time4.google.com

# Fetch the ssh keys for the users here
user_ssh_keys:
  - { name: "mhahl", url: https://github.com/mhahl.keys }

# Alias workstations to the hosts that are considered workstations.
hbac_sudo_hosts:
  - name: WORKSTATIONS
    hosts:
      - huon.sigaint.au
      - pine.sigaint.au
      - laptop*.sigaint.au
      - workstation*.sigaint.au

hbac_sudo_commands: []
##  - name: REBOOT
##    commands:
##      - /sbin/reboot
##      - /sbin/poweroff

hbac_sudo_runas:
  # Allow administrators to run any commands as root
  # without a password.
  #
  - name: "%grp-sigaint-admins"
    hosts:
      - ALL
    options:
      - NOPASSWD
    users:
      - root
    groups:
      - operator
    commands:
      - ALL

  # On Workstations and Laptops allow the user to run
  # the following commands as root without a password.
  # These machines are mostly treated as personal machines.
  #
  - name: "%grp-sigaint-users"
    hosts:
      - WORKSTATIONS
    options:
      - NOPASSWD
    users:
      - root
    groups:
      - operator
    commands:
      - ALL
