---
- name: sigaint-soe | repos | create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /usr/local/etc/pkg/repos/

- name: sigaint-soe | repos | deploy file templates
  ansible.builtin.template:
    src: "../templates/{{ item.template }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items:
    - { template: pkg/FreeBSD.conf, dest: /usr/local/etc/pkg/repos/FreeBSD.conf, mode: "0644" }