---

- name: sigaint-soe | baseline | deploy file templates
  ansible.builtin.template:
    src: "../templates/{{ item.template }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  when: ansible_distribution in item.distribution
  with_items:
    - { template: cron/baseline, dest: /etc/cron.d/baseline, mode: "0644" }
