###########################
# Depending on which operating system is being used, import the appropriate DNS configuration task file.
# On FreeBSD we update the resolv.conf
# but on fedora we want to configure systemd-resolved with DNSoverTLS instead.
#
- ansible.builtin.import_tasks: "dns/resolv_conf.yaml"
  when: ansible_facts['ansible_distribution'].lower() in ['freebsd']

- ansible.builtin.import_tasks: "dns/systemd_resolved.yaml"
  when: ansible_facts['ansible_distribution'].lower() in ['fedora']
