---
- name: system-baseline | Configure DNS
  tags:
    - dns
    - dns:configure
  block:
    - name: dns | Configure nameservers
      ansible.builtin.template:
        src: "../templates/dns/resolv.conf.j2"
        dest: "/etc/resolv.conf"
        mode: "0755"
        owner: "root"
        group: "wheel"
      tags:
        - baseline:dns
        - baseline:dns:configure
