---
- name:
  tags:
    - moonlight
  ansible.builtin.uri:
    url: "{{moonlight_api}}"
    method: POST
    body_format: json
    status_code: 204
    failed_when: false
    body: |
      {
        "machine": {
          "uuid": "{{ ansible_fqdn }}",
          "token": "{{ansible_facts['machine_id']}}",
          "ansible_facts": {{ ansible_facts | to_json }},
        }
      }