---

- include_tasks: "playbooks/ntp/ntpd.yaml"
  when: "{{ ansible_distribution | lower in ['freebsd']}}"

- include_tasks: "playbooks/ntp/chrony.yaml"
  when: "{{ ansible_distribution | lower in ['fedora']}}"
