- name: system-baseline | create directories
  ansible.builtin.file:
    path: "{{item}}"
    state: directory
  with_items:
    - /home
    - /usr/local/etc/pkg/repos
    - /usr/share/skel
    - /usr/local/etc/baseline
  tags:
    - baseline
    - baseline:directories

- name: system-baseline | install packages
  package:
    name:
      - sssd2
      - bash
      - pam_mkhomedir
      - sudo
  tags:
    - baseline
    - baseline:packages

