---
##
# Skel is the templaes that get copied over when pam_mkhomedir
# creates the user on first login.
#
# Any changes to thse templates dont automatically update
# the files in the home drive.
#
- name: baseline-freebsd | skel | install packages
  ansible.builtin.package:
    name:
      - bash
      - pam_mkhomedir
  tags:
    - baseline:skel
    - baseline:skel:packages

- name: baseline-freebsd | skel | create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /home
    - /usr/share/skel
  tags:
    - baseline:skel
    - baseline:skel:directories

- name: baseline-freebsd | Deploy file templates
  ansible.builtin.template:
    src: "../templates/{{ item.template }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  tags:
    - baseline:skel
    - baseline:skel:packages
  with_items:
    - { template: skel/dot.bashrc, dest: /usr/share/skel/dot.bashrc, mode: "0644" }
    - { template: skel/dot.bash_profile, dest: /usr/share/skel/dot.bash_profile, mode: "0644" }
