##
# Skel is the templaes that get copied over when pam_mkhomedir
# creates the user on first login.
#
# Any changes to thse templates dont automatically update
# the files in the home drive.
#
- name: baseline-freebsd | skel | install packages
  package:
    name:
      - pam_mkhomedir
  tags:
    - baseline:skel
    - baseline:skel:packages

- name: baseline-freebsd | deploy file templates
  ansible.builtin.template:
    src: "../templates/{{item.template}}"
    dest: "{{item.dest}}"
    mode: "{{item.mode}}"
  tags:
    - baseline:skel
    - baseline:skel:packages
  with_items:
    # Skel
    - { template: skel/dot.bashrc,  dest: /usr/share/skel/dot.bashrc, mode: "0644" }
    - { template: skel/dot.bash_profile,  dest: /usr/share/skel/dot.bash_profile, mode: "0644" }
