---
- name: freebsd-baseline | sudoers | install packages
  package:
    name:
      - sudo
  tags:
    - baseline:sudoers
    - baseline:sudoers:packages

- name: freebsd-baseline | sudoers | deploy templates
  ansible.builtin.template:
    src: "../templates/{{ item.template }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items:
    # Sudo
    - { template: sudoers/sudoers, dest: /usr/local/etc/sudoers, mode: "0440" }
