---

- name: sigaint-soe | timezone | get file stats
  ansible.builtin.stat:
    path: /etc/localtime
  register: sym
  tags:
    - baseline:timezone
    - baseline:timezone:configure

- name: sigaint-soe | timezone | remove localtime if not a symlink
  ansible.builtin.file:
    path: "/etc/localtime"
    state: absent
  when: sym.stat.islnk is defined and not sym.stat.islnk
  tags:
    - baseline:timezone
    - baseline:timezone:configure

- name: sigaint-soe | timezone | set timezone
  ansible.builtin.file:
    src: "/usr/share/zoneinfo/{{ timezone }}"
    dest: /etc/localtime
    state: link
  tags:
    - baseline:timezone
    - baseline:timezone:configure